In [1]:
#Revision 

#Series : A 1 D data strucutre

import pandas as pd

s = pd.Series([1,2,3,4,5],index=["Mine","You","YourBro","Nitish","rohan"])
# print(s[1])

#Data frame : 2D Tabular-Data structure (Rows + Column)

Data = {
    'Name':["Virat","Rohit","Sachin"],
    'Age':[23,121,2],
    'Runs':[23,100,200]

}

df = pd.DataFrame(Data)
# print(df)
# print(df.shape)
# df.head(1)#Acess first row 
# df.tail(1)#Acess last row

# df.info()
# RoundedNums = round(df.describe(),2)
# print(RoundedNums)

# df['Name']
# df[['Name','Age']]

#Reading CSV files/Excel files

# df = pd.read_csv("Demo.csv")
# df=pd.read_csv("Demo.csv",header=None)
# df=pd.read_csv('Demo.csv',=["A","B","C"])
print(df)
#Most important 5 rules after loading data
# df.head()
# df.tail()
df.shape
# df.info()
df.columns

     Name  Age  Runs
0   Virat   23    23
1   Rohit  121   100
2  Sachin    2   200

Index(['Name', 'Age', 'Runs'], dtype='object')

In [2]:
#CSV file handling 

import pandas as pd

# df =pd.read_csv("Demo.csv")

df = pd.read_excel("DemoPandasData.xlsx",sheet_name="SalesOrders")
# print(df)

df['Region']
df[['Region','Item']]
df[(df['Units']>30) & (df['Units']<40)]

df[(df['Unit Cost']<=10) | (df["Unit Cost"] == 10)]

df[df['Region']=='East'][["Rep","Units"]]#Jis Rep , Units ka region East hai 

df[df['Region'].isin(['East','Central'])]

df[df['Units'].between(80,90)]

    OrderDate   Region      Rep    Item  Units  Unit Cost    Total
7  2024-05-05  Central  Jardine  Pencil     90       4.99   449.10
10 2024-06-25  Central   Morgan  Pencil     90       4.99   449.10
12 2024-07-29     East   Parent  Binder     81      19.99  1619.19
23 2025-02-01  Central    Smith  Binder     87      15.00  1305.00
30 2025-05-31  Central     Gill  Binder     80       8.99   719.20

In [3]:
#iloc vs Loc

import pandas as pd

df = pd.read_excel('DemoPandasData.xlsx',sheet_name="SalesOrders")
# print(df)
#Row selection 
df.iloc[0]

#Row+column
df.iloc[0,1]

df.iloc[:,1:3]

#loc(Label-based)

df.loc[0]

df.loc[1:3,:]

df.loc[:,['Region','Units']]

#loc with conditioning 

df.loc[df['Units']>80,['Region','Rep']]#80 se jada units wale region and rep

     Region      Rep
0      East    Jones
7   Central  Jardine
10  Central   Morgan
12     East   Parent
19  Central   Kivell
23  Central    Smith
28     East   Howard
41  Central  Jardine

In [4]:
#Missing Values and Duplicate Handling 

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Riya', 'Rohit', 'Neha'],
    'Marks': [85, np.nan, np.nan, 78, 88],
    'City': ['Delhi', 'Mumbai', 'Mumbai', np.nan, 'Pune']
})


df.isnull()

df.isnull().sum()



# df.dropna()
df.dropna(axis=1)#Very Dangerous

# df['Marks'] = df['Marks'].fillna(df['Marks'].mean())


df.ffill()
df.bfill()

df.duplicated()
df.drop_duplicates()

# df.drop_duplicates(subset=['Name'])

    Name  Marks    City
0   Aman   85.0   Delhi
1   Riya    NaN  Mumbai
3  Rohit   78.0     NaN
4   Neha   88.0    Pune

In [5]:
#Exercises

#Easy
import pandas as pd

Data= {
   'Name':["Virat","Virat","Sachin"],
    'Age':[123,123,2],
    'City':["Jaipur","Jaipur",np.nan]
}

df = pd.DataFrame(Data)
# df.head()
# df.info()

# df['Age'].info()

df[df['Age']>20]


df.isnull().sum()

df.drop_duplicates()

     Name  Age    City
0   Virat  123  Jaipur
2  Sachin    2     NaN

In [6]:
#Medium Exercises

import pandas as pd
import numpy as np 



df = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106, 107],
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Karan', 'Riya'],
    'Age': [20, 21, 19, 22, 20, np.nan, 21],
    'Marks': [85, 92, 78, 88, 85, 90, np.nan],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Mumbai']
})


df[(df['City']=='Delhi') & (df['Age']>19)]

df[df['Age'].between(18,22)][['Name','Age']]

df.loc[df['City']=="Mumbai",['Name','Age']]

print(df)

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)


df.iloc[2:4,1:3]

   StudentID   Name   Age  Marks    City
0        101   Aman  20.0   85.0   Delhi
1        102   Riya  21.0   92.0  Mumbai
2        103  Rohit  19.0   78.0   Delhi
3        104   Neha  22.0   88.0    Pune
4        105   Aman  20.0   85.0   Delhi
5        106  Karan   NaN   90.0  Mumbai
6        107   Riya  21.0    NaN  Mumbai
   StudentID   Name   Age      Marks    City
0        101   Aman  20.0  85.000000   Delhi
1        102   Riya  21.0  92.000000  Mumbai
2        103  Rohit  19.0  78.000000   Delhi
3        104   Neha  22.0  88.000000    Pune
4        105   Aman  20.0  85.000000   Delhi
5        106  Karan   NaN  90.000000  Mumbai
6        107   Riya  21.0  86.333333  Mumbai

    Name   Age
2  Rohit  19.0
3   Neha  22.0

In [7]:
#hard exercises 

import pandas as pd
import numpy as np 



df = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106, 107],
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Karan', 'Riya'],
    'Age': [20, 21, 19, 22, 20, np.nan, 21],
    'Marks': [85, 92, 78, 88, 85, 90, np.nan],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Mumbai']
})
df[df['Marks']>80].loc[:,["Name","Marks"]]


df.drop_duplicates(subset=['Name'])
# df[:]


# pd.read_csv("data.csv",sep=";")

# loc : label based filtering its a inclusive
# iloc : index based filtering its a exclusiv

#Reason : Yeh ekk tuple bana jata hai Yah toh LOC use karo [[ ..]]
CorrectVersion = df[df["Marks"]>80]['Name',"Marks"]

KeyError: ('Name', 'Marks')

In [ ]:
#Group By 
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Karan', 'Riya'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Mumbai'],
    'Marks': [85, 92, 78, 88, 85, 90, np.nan],
    'Age': [20, 21, 19, 22, 20, np.nan, 21]
})
# print(df[:])
df.groupby('City')['Age'].mean()

#Group + Multiple aggregration 

df.groupby('City')['Marks'].agg(['mean','max','min'])

#Groupby + count

df.groupby('City').size()

#Groupby Multiple columns

df.groupby(['City','Name'])['Marks'].mean()

#reset_index()
df.groupby('City')['Marks'].mean().reset_index()
'''
Jab hum normal filter karte hai tab index ulte sidhe hote obviously 
but reset_index() unhe wapis order mein kardeta hai 
'''

#Exercise 

df.groupby('City')['Marks'].mean()
df.groupby("City")['Marks'].max()

df.groupby('City').size()#.size() NaN values ko bhi count karta hai 
df.groupby('City')['Marks'].agg(['mean','max'])

df.groupby("City")["Marks"].mean().reset_index()

# mcq =[c,c,b,c,b]

     City      Marks
0   Delhi  82.666667
1  Mumbai  91.000000
2    Pune  88.000000

In [ ]:
#Data types and Date analysis

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rohit'],
    'Marks': ['85', '90', '78'],
    'Age': [20, np.nan, 19],
    'JoinDate': ['2023-01-10', '2023-02-15', '2023-03-20']
})

df.dtypes
df['Marks'].astype('int')

# df['Age']=df[df]

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age']

df['Age'].astype(int)
df['JoinDate'] = pd.to_datetime(df['JoinDate'])
df['JoinDate']
df["JoinYear"] = df['JoinDate'].dt.year
df['JoinMonth'] = df["JoinDate"].dt.month


df['JoinYear']
df['JoinMonth']

MCQ = ["C","A","B","A","C"]

0    1
1    2
2    3
Name: JoinMonth, dtype: int32

In [ ]:
#Sorting and Counting 
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Riya'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai'],
    'Marks': [85, 92, 78, 88, 85, 92],
    'Age': [20, 21, 19, 22, 20, 21]
})

#Ascending(default): sort data into ascending order 

df.sort_values('Marks')#values ko ascending order ke base pe sort karna 
df.sort_values('Marks' , ascending=False) #sirf marks ke column ko descending order mein sort kiya 

#Multiple Columns pe sort 
df.sort_values(['City','Marks'],ascending=False) # Isme Marks ko toh kiya sort lekin saath mein unke align city thi unko bhi sort kardiya 

#Query : "Highest marks wale students dikhao "

#Value Counts

df['City'].value_counts() # har city mein kite students hai 
df['City'].value_counts(normalize=True) # Percentage waise dikhata hai 

#Unique()

df['City'].unique() # NUmpy array mein ans aaata hai 
df['City'].nunique() # count of unique values 
df['City'].value_counts().head(2)# Top 2 cities with higher count 

#Exercise 

df.sort_values(
'Marks',ascending=False
)

df['City'].value_counts()
df['City'].unique()
df['City'].nunique()
df['City'].value_counts().head(2)

MCQ = "cBdcc"

City
Delhi     3
Mumbai    2
Name: count, dtype: int64

In [8]:
#Merge Join and concat 

import pandas as pd

students = pd.DataFrame({
    'StudentID': [101, 102, 103, 104],
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune']
})

marks = pd.DataFrame({
    'StudentID': [101, 102, 104, 105],
    'Marks': [85, 92, 88, 90]
})
print(students)
print(marks)

# 1. Merge (Inner Join , Left JOin , RIght Join , Outer JOin )

#Inner JOin(default) 
pd.merge(students,marks,on='StudentID')
#sirf common student id aaenga 

#LEft Join 

pd.merge(students,marks,on='StudentID',how='left')
#left table ke sabhi rows likhenge aur agar value missing hui toh NaN ka use karenge 

#Right Join 

pd.merge(students,marks,on='StudentID',how='right')

#Outer Join 
pd.merge(students,marks,on='StudentID',how='outer')

#2 concat()

pd.concat([students,marks]) #Row wise concat

pd.concat([students,marks],axis=1)

#index based merge 
students.set_index('StudentID').join(marks.set_index('StudentID'))#jab index same ho join clearn hota hai 

#merge() is used to combine DataFrames using common columns,
# while concat() stacks DataFrames vertically or horizontally.

   StudentID   Name    City
0        101   Aman   Delhi
1        102   Riya  Mumbai
2        103  Rohit   Delhi
3        104   Neha    Pune
   StudentID  Marks
0        101     85
1        102     92
2        104     88
3        105     90

            Name    City  Marks
StudentID
101         Aman   Delhi   85.0
102         Riya  Mumbai   92.0
103        Rohit   Delhi    NaN
104         Neha    Pune   88.0

In [ ]:
#

2.4.0
2.3.3