In [ ]:
#Revision

#Series : A 1 D data strucutre

import pandas as pd

s = pd.Series([1,2,3,4,5],index=["Mine","You","YourBro","Nitish","rohan"])
# print(s[1])

#Data frame : 2D Tabular-Data structure (Rows + Column)

Data = {
    'Name':["Virat","Rohit","Sachin"],
    'Age':[23,121,2],
    'Runs':[23,100,200]

}

df = pd.DataFrame(Data)
# print(df)
# print(df.shape)
# df.head(1)#Acess first row
# df.tail(1)#Acess last row

# df.info()
# RoundedNums = round(df.describe(),2)
# print(RoundedNums)

# df['Name']
# df[['Name','Age']]

#Reading CSV files/Excel files

# df = pd.read_csv("Demo.csv")
# df=pd.read_csv("Demo.csv",header=None)
# df=pd.read_csv('Demo.csv',=["A","B","C"])
print(df)
#Most important 5 rules after loading data
# df.head()
# df.tail()
df.shape
# df.info()
df.columns

In [ ]:
#CSV file handling

import pandas as pd

# df =pd.read_csv("Demo.csv")

df = pd.read_excel("DemoPandasData.xlsx",sheet_name="SalesOrders")
# print(df)

df['Region']
df[['Region','Item']]
df[(df['Units']>30) & (df['Units']<40)]

df[(df['Unit Cost']<=10) | (df["Unit Cost"] == 10)]

df[df['Region']=='East'][["Rep","Units"]]#Jis Rep , Units ka region East hai

df[df['Region'].isin(['East','Central'])]

df[df['Units'].between(80,90)]

In [ ]:
#iloc vs Loc

import pandas as pd

df = pd.read_excel('DemoPandasData.xlsx',sheet_name="SalesOrders")
# print(df)
#Row selection
df.iloc[0]

#Row+column
df.iloc[0,1]

df.iloc[:,1:3]

#loc(Label-based)

df.loc[0]

df.loc[1:3,:]

df.loc[:,['Region','Units']]

#loc with conditioning

df.loc[df['Units']>80,['Region','Rep']]#80 se jada units wale region and rep

In [ ]:
#Missing Values and Duplicate Handling

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Riya', 'Rohit', 'Neha'],
    'Marks': [85, np.nan, np.nan, 78, 88],
    'City': ['Delhi', 'Mumbai', 'Mumbai', np.nan, 'Pune']
})


df.isnull()

df.isnull().sum()



# df.dropna()
df.dropna(axis=1)#Very Dangerous

# df['Marks'] = df['Marks'].fillna(df['Marks'].mean())


df.ffill()
df.bfill()

df.duplicated()
df.drop_duplicates()

# df.drop_duplicates(subset=['Name'])

In [ ]:
#Exercises

#Easy
import pandas as pd

Data= {
   'Name':["Virat","Virat","Sachin"],
    'Age':[123,123,2],
    'City':["Jaipur","Jaipur",np.nan]
}

df = pd.DataFrame(Data)
# df.head()
# df.info()

# df['Age'].info()

df[df['Age']>20]


df.isnull().sum()

df.drop_duplicates()

     Name  Age    City
0   Virat  123  Jaipur
2  Sachin    2     NaN

In [ ]:
#Medium Exercises

import pandas as pd
import numpy as np



df = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106, 107],
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Karan', 'Riya'],
    'Age': [20, 21, 19, 22, 20, np.nan, 21],
    'Marks': [85, 92, 78, 88, 85, 90, np.nan],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Mumbai']
})


df[(df['City']=='Delhi') & (df['Age']>19)]

df[df['Age'].between(18,22)][['Name','Age']]

df.loc[df['City']=="Mumbai",['Name','Age']]

print(df)

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)


df.iloc[2:4,1:3]

In [ ]:
#hard exercises

import pandas as pd
import numpy as np



df = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106, 107],
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Karan', 'Riya'],
    'Age': [20, 21, 19, 22, 20, np.nan, 21],
    'Marks': [85, 92, 78, 88, 85, 90, np.nan],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Mumbai']
})
df[df['Marks']>80].loc[:,["Name","Marks"]]


df.drop_duplicates(subset=['Name'])
# df[:]


# pd.read_csv("data.csv",sep=";")

# loc : label based filtering its a inclusive
# iloc : index based filtering its a exclusiv

#Reason : Yeh ekk tuple bana jata hai Yah toh LOC use karo [[ ..]]
CorrectVersion = df[df["Marks"]>80]['Name',"Marks"]

   StudentID   Name   Age  Marks    City
0        101   Aman  20.0   85.0   Delhi
1        102   Riya  21.0   92.0  Mumbai
2        103  Rohit  19.0   78.0   Delhi
3        104   Neha  22.0   88.0    Pune
5        106  Karan   NaN   90.0  Mumbai

In [ ]:
#Group By
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rohit', 'Neha', 'Aman', 'Karan', 'Riya'],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Mumbai'],
    'Marks': [85, 92, 78, 88, 85, 90, np.nan],
    'Age': [20, 21, 19, 22, 20, np.nan, 21]
})
# print(df[:])
df.groupby('City')['Marks'].mean()

    Name    City  Marks   Age
0   Aman   Delhi   85.0  20.0
1   Riya  Mumbai   92.0  21.0
2  Rohit   Delhi   78.0  19.0
3   Neha    Pune   88.0  22.0
4   Aman   Delhi   85.0  20.0
5  Karan  Mumbai   90.0   NaN
6   Riya  Mumbai    NaN  21.0

City
Delhi     82.666667
Mumbai    91.000000
Pune      88.000000
Name: Marks, dtype: float64

In [1]:
print("Hello from Google Colab ")

Hello from Google Colab